// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yduiaxjgolkiaydilfux.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkdWlheGpnb2xraWF5ZGlsZnV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzM4MjIsImV4cCI6MjA3MzYwOTgyMn0.Ws16Qu16E98shNmhR5_myYnd7mUWPbLnI64iJZLvu6o";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);